"""Embeds the UI fonts into the plugin (src/lib/fonts.ts), so Spotlog makes no requests to Google Fonts.

assets/fonts holds small subsets (SIL Open Font License, see OFL-*.txt):
  - Instrument Sans variable (weights 400–600), Latin + Latin Extended-A (Czech, Polish, German, Spanish…)
  - Doto 900, only A–Z, a–z, 0–9 and . , - – +  (wordmark and the big forecast numbers)
They were made from @fontsource-variable/instrument-sans and @fontsource/doto with fontTools:
  pip install fonttools brotli
  fonttools varLib.instancer instrument-sans-latin-wght-normal.woff2 wght=400:600 -o is.ttf
  pyftsubset is.ttf --flavor=woff2 --unicodes="U+0020-007E,U+00A0-00FF,U+2013-2014,U+2018-201D,U+2022,U+2026,U+20AC,U+2190-2193,U+2212" \
      --output-file=instrument-sans-latin-wght400-600.woff2      (same for latin-ext with U+0100-017F,U+0218-021B)
  pyftsubset doto-latin-900-normal.woff2 --flavor=woff2 --text="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789.,-–+ " --output-file=doto-900-subset.woff2

Run after changing fonts:  python3 scripts/build-fonts.py
"""
import base64, pathlib
root = pathlib.Path(__file__).resolve().parent.parent
d = root / 'assets' / 'fonts'
LATIN = 'U+0020-007E,U+00A0-00FF,U+2009,U+2013-2014,U+2018-2019,U+201C-201D,U+2022,U+2026,U+202F,U+2032-2033,U+2039-203A,U+20AC,U+2122,U+2190-2193,U+2212'
LATIN_EXT = 'U+0100-017F,U+0218-021B'
faces = []
def face(family, weight, file, rng):
    b64 = base64.b64encode((d / file).read_bytes()).decode()
    faces.append(f"@font-face{{font-family:'{family}';font-style:normal;font-display:swap;font-weight:{weight};"
                 f"src:url(data:font/woff2;base64,{b64}) format('woff2');unicode-range:{rng}}}")
face('Instrument Sans', '400 600', 'instrument-sans-latin-wght400-600.woff2', LATIN)
face('Instrument Sans', '400 600', 'instrument-sans-latin-ext-wght400-600.woff2', LATIN_EXT)
face('Doto', 900, 'doto-900-subset.woff2', 'U+0020-005A,U+0061-007A')
out = root / 'src' / 'lib' / 'fonts.ts'
out.write_text(
    '// Generated by scripts/build-fonts.py — do not edit by hand.\n'
    '// Instrument Sans + Doto subsets, SIL Open Font License 1.1 (assets/fonts/OFL-*.txt).\n'
    f'export const FONT_CSS = {repr(chr(10).join(faces))};\n'
)
print(out, round(out.stat().st_size / 1024), 'KB')
