"""Embeds the UI fonts into the plugin (src/lib/fonts.ts), so Spotlog makes no requests to Google Fonts.
Fonts: Instrument Sans 400/500/600 (latin + latin-ext) and Doto 900 (latin), SIL Open Font License (see assets/fonts).
Run after changing fonts:  python3 scripts/build-fonts.py
"""
import base64, pathlib
root = pathlib.Path(__file__).resolve().parent.parent
d = root / 'assets' / 'fonts'
LATIN = 'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD'
LATIN_EXT = 'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF'
faces = []
def face(family, weight, file, rng):
    b64 = base64.b64encode((d / file).read_bytes()).decode()
    faces.append(f"@font-face{{font-family:'{family}';font-style:normal;font-display:swap;font-weight:{weight};"
                 f"src:url(data:font/woff2;base64,{b64}) format('woff2');unicode-range:{rng}}}")
for w in (400, 500, 600):
    face('Instrument Sans', w, f'instrument-sans-latin-{w}-normal.woff2', LATIN)
    face('Instrument Sans', w, f'instrument-sans-latin-ext-{w}-normal.woff2', LATIN_EXT)
face('Doto', 900, 'doto-latin-900-normal.woff2', LATIN)
out = root / 'src' / 'lib' / 'fonts.ts'
out.write_text(
    '// Generated by scripts/build-fonts.py — do not edit by hand.\n'
    '// Instrument Sans + Doto, SIL Open Font License 1.1 (assets/fonts/OFL-*.txt).\n'
    f'export const FONT_CSS = {repr(chr(10).join(faces))};\n'
)
print(out, round(out.stat().st_size / 1024), 'KB')
